cloud:
  aws:
    s3:
      bucket: ownspacebucket
    credentials:
      access-key: ${aws_access_key_id}
      secret-key: ${aws_secret_access_key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OwnSpace?serverTimezone=Asia/Seoul
    username: root
    password: ${my_sql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create  # 스키마 자동생성. 개발 환경에서만 사용
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 15MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

jasypt:
  encryptor:
    password: test

# sql 로깅
logging.level:
  org.hibernate.orm.jdbc.bind: trace
  org.hibernate.type: trace
