cloud:
  aws:
    s3:
      bucket: ownspacebucket
    credentials:
      access-key: AKIATLDZ3C2MYN5APH6W
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량